/**
 * Stage 4: pass output becomes an FFIR document.
 *
 * Local, deterministic, and fully specified. Every field is copied from a pass,
 * derived from the registry, or stamped by the caller. Nothing is invented
 * here, and that is the point: a field the merge derives is a field the model
 * cannot hallucinate.
 *
 * ## Sentinels become absence
 *
 * The pass schemas require every field so the shape stays closed, which means
 * optionality is expressed with sentinel values. This is where they are
 * converted back:
 *
 * | Pass output | FFIR result |
 * | --- | --- |
 * | `notes: ""` | Field omitted. |
 * | `condition_operator: "none"` | The whole `condition` object omitted. |
 * | `retry_attempts: 0` | `error_policy.retry` omitted. |
 * | `on_error: "stop"` with `retry_attempts: 0` | `error_policy` omitted entirely. |
 * | `default: ""` on a variable | Field omitted. |
 * | `port: ""` | Omitted, which is how FFIR spells `"main"`. |
 *
 * ## Credential scope is derived, not read
 *
 * AI_SPEC has the merge join `capability_scope` from the plan against the
 * registry's auth definitions. This does the join against the integration the
 * capability actually resolves to instead, because they are the same value for
 * any well-formed plan and only the derived one is right when the model gets it
 * wrong. That removes a hallucination surface outright rather than validating
 * it afterwards. The plan's own `capability_scope` is still read, and a
 * disagreement is recorded as a warning, because a model contradicting a value
 * it could have derived is a prompt-quality signal worth counting.
 *
 * ## The clock and the id come from the caller
 *
 * `generated_at` and the document id are arguments, not calls to `Date.now()`
 * and a UUID generator. The merge is therefore a pure function of its inputs
 * and a fixture-driven test asserts on a whole document rather than on a
 * document with two fields excused. The orchestrator owns the clock.
 */

import { createHash } from "node:crypto";

import {
  isSecretFieldName,
  SUPPORTED_EXPRESSION_GRAMMARS,
  SUPPORTED_FFIR_VERSIONS,
  UNARY_CONDITION_OPERATORS,
  type Condition,
  type ConditionOperator,
  type CredentialRef,
  type Edge,
  type ErrorPolicy,
  type FFIRDocument,
  type Node,
  type NodeKind,
  type OnError,
  type Variable,
  type VariableType,
  type Warning,
} from "@flowforge/ffir";
import {
  compareStrings,
  resolve,
  type AuthDefinition,
  type Registry,
} from "@flowforge/registry";

import { NO_CONDITION, type PlanEdge, type PlanNode, type WorkflowPlan } from "./passes/plan.js";
import type { NodeParameters } from "./passes/parameters.js";

/**
 * The versions this writer emits.
 *
 * Constants rather than "the newest supported", because a build that starts
 * emitting a version the day it learns to read it would migrate every stored
 * workflow by accident. A test pins both against the supported lists.
 */
export const WRITES_FFIR_VERSION = "1.0";
export const WRITES_EXPRESSION_GRAMMAR = "1";

/**
 * Retry shape the plan does not carry.
 *
 * Pass A emits an attempt count and nothing else, because asking a model to
 * choose a backoff strategy invites it to choose badly and the right answer is
 * the same almost every time. Exponential from two seconds is what the worked
 * example uses and what a rate-limited API wants.
 */
export const DEFAULT_RETRY_BACKOFF = "exponential" as const;
export const DEFAULT_RETRY_INITIAL_DELAY_MS = 2000;

/** Prefix for a derived credential id. `cred_slack`, `cred_bamboohr`. */
const CREDENTIAL_PREFIX = "cred_";

export const MERGE_WARNING_CODES = [
  /** The plan's `capability_scope` disagreed with the capability's integration. */
  "capability_scope_ignored",
  /** The heuristic promoted a variable to sensitive, stripping any default. */
  "variable_marked_sensitive",
  /** Pass B returned no entry for a planned node. Its parameters are empty. */
  "node_parameters_missing",
] as const;
export type MergeWarningCode = (typeof MERGE_WARNING_CODES)[number];

export interface MergeInput {
  plan: WorkflowPlan;
  parameters: NodeParameters;
  registry: Registry;
  /** The user's request. Hashed into metadata; never stored verbatim. */
  prompt: string;
  /** Generated by the orchestrator, or carried through on iteration. */
  documentId: string;
  /** ISO 8601. Supplied so this function has no clock. */
  generatedAt: string;
  /** The model that produced the plan. */
  generatedBy: string;
  promptVersion: string;
  /** Warnings accumulated by earlier stages, carried onto the document. */
  warnings?: readonly Warning[];
}

export interface MergeResult {
  document: FFIRDocument;
  warnings: Warning[];
}

export function merge(input: MergeInput): MergeResult {
  const warnings: Warning[] = [...(input.warnings ?? [])];

  const credentials = deriveCredentials(input.plan, input.registry, warnings);
  const credentialByScope = new Map(
    credentials.map((credential) => [credential.capability_scope, credential.id]),
  );

  const nodes = input.plan.nodes.map((node) =>
    toNode(node, input, credentialByScope, warnings),
  );
  const edges = input.plan.edges.map(toEdge);
  const variables = input.plan.variables.map((variable) =>
    toVariable(variable, warnings),
  );

  const document: FFIRDocument = {
    ffir_version: WRITES_FFIR_VERSION,
    expression_grammar: WRITES_EXPRESSION_GRAMMAR,
    id: input.documentId,
    name: input.plan.name,
    description: input.plan.description,
    nodes,
    edges,
    credentials,
    ...(variables.length === 0 ? {} : { variables }),
    metadata: {
      generated_by: input.generatedBy,
      generated_at: input.generatedAt,
      source_prompt_hash: hashPrompt(input.prompt),
      registry_version: input.registry.version,
      prompt_version: input.promptVersion,
      ...(warnings.length === 0 ? {} : { warnings }),
    },
  };

  return { document, warnings };
}

/** sha256, hex. The prompt itself is never stored: this is for correlation. */
export function hashPrompt(prompt: string): string {
  return createHash("sha256").update(prompt, "utf8").digest("hex");
}

// ---------------------------------------------------------------------------
// Nodes
// ---------------------------------------------------------------------------

function toNode(
  planned: PlanNode,
  input: MergeInput,
  credentialByScope: ReadonlyMap<string, string>,
  warnings: Warning[],
): Node {
  const parameters = input.parameters[planned.id];
  if (parameters === undefined) {
    warnings.push({
      code: "node_parameters_missing",
      node_id: planned.id,
      message: `No parameter values were produced for "${planned.label}". The step is in the workflow but unconfigured, and will need filling in by hand.`,
    });
  }

  const scope = scopeOf(planned, input.registry);
  const credential =
    scope === undefined ? undefined : credentialByScope.get(scope);
  const errorPolicy = toErrorPolicy(planned);

  return {
    id: planned.id,
    kind: planned.kind as NodeKind,
    capability: planned.capability,
    label: planned.label,
    parameters: parameters ?? {},
    ...(credential === undefined ? {} : { credential }),
    ...(errorPolicy === undefined ? {} : { error_policy: errorPolicy }),
    ...(planned.notes === "" ? {} : { notes: planned.notes }),
  };
}

/**
 * `error_policy` is omitted entirely when it would say nothing.
 *
 * The compiler applies `stop` and no retry as its own defaults, so writing them
 * out produces a document that differs from a hand-written one for no
 * behavioural reason. A blueprint should show the decisions a workflow actually
 * made.
 */
function toErrorPolicy(planned: PlanNode): ErrorPolicy | undefined {
  const attempts = planned.retry_attempts;
  const onError = planned.on_error as OnError;

  if (onError === "stop" && attempts <= 0) return undefined;

  return {
    on_error: onError,
    ...(attempts > 0
      ? {
          retry: {
            attempts,
            backoff: DEFAULT_RETRY_BACKOFF,
            initial_delay_ms: DEFAULT_RETRY_INITIAL_DELAY_MS,
          },
        }
      : {}),
  };
}

// ---------------------------------------------------------------------------
// Edges
// ---------------------------------------------------------------------------

function toEdge(planned: PlanEdge): Edge {
  const condition = toCondition(planned);
  return {
    id: planned.id,
    from: planned.from,
    to: planned.to,
    // FFIR spells the default port by leaving the field off. Writing `"main"`
    // out would be legal and would make every generated document differ from
    // the worked example for no reason.
    ...(planned.port === "" || planned.port === "main" ? {} : { port: planned.port }),
    ...(condition === undefined ? {} : { condition }),
  };
}

function toCondition(planned: PlanEdge): Condition | undefined {
  if (planned.condition_operator === NO_CONDITION) return undefined;

  const operator = planned.condition_operator as ConditionOperator;
  // The FFIR schema forbids `right` on a unary operator outright, so a model
  // that filled the sentinel in anyway must not have it carried through.
  const unary = (UNARY_CONDITION_OPERATORS as readonly string[]).includes(operator);

  return {
    left: planned.condition_left,
    operator,
    ...(unary ? {} : { right: planned.condition_right }),
  };
}

// ---------------------------------------------------------------------------
// Variables
// ---------------------------------------------------------------------------

/**
 * Model judgment is trusted to add the sensitive flag, never to remove it.
 *
 * A variable the model marked sensitive stays sensitive. One it did not is
 * promoted when its id or label reads like a credential, and its default is
 * stripped, because rule 15 forbids a sensitive variable from carrying one and
 * because a default on a secret is a secret in the document.
 */
function toVariable(
  planned: WorkflowPlan["variables"][number],
  warnings: Warning[],
): Variable {
  const suspicious =
    isSecretFieldName(planned.id) || isSecretFieldName(planned.label);
  const sensitive = planned.sensitive || suspicious;

  if (sensitive && !planned.sensitive) {
    warnings.push({
      code: "variable_marked_sensitive",
      message:
        `Variable "${planned.id}" was marked sensitive because its name reads like a credential` +
        (planned.default === ""
          ? "."
          : `, and its default value was removed. A default on a secret is a secret stored in the workflow.`),
    });
  }

  return {
    id: planned.id,
    label: planned.label,
    type: planned.type as VariableType,
    required: planned.required,
    sensitive,
    ...(sensitive || planned.default === "" ? {} : { default: planned.default }),
    ...(planned.description === "" ? {} : { description: planned.description }),
  };
}

// ---------------------------------------------------------------------------
// Credentials
// ---------------------------------------------------------------------------

/**
 * One credential per integration the workflow authenticates against.
 *
 * `required_scopes` is the union across every capability using that credential,
 * so the setup guide asks for exactly the permissions the workflow needs and no
 * more. That is a real security property, not tidiness: a guide that cannot say
 * what is needed pushes people toward granting everything.
 *
 * A capability with no `auth_required`, which is every `core.*` one, produces no
 * credential and no reference on its node.
 */
function deriveCredentials(
  plan: WorkflowPlan,
  registry: Registry,
  warnings: Warning[],
): CredentialRef[] {
  const byScope = new Map<string, { auth: AuthDefinition; scopes: Set<string> }>();

  for (const node of plan.nodes) {
    const resolved = resolve(registry, node.capability);
    if (resolved?.auth === undefined) continue;

    const scope = resolved.integration.integration;
    const existing = byScope.get(scope);
    const entry = existing ?? { auth: resolved.auth, scopes: new Set<string>() };
    for (const required of resolved.capability.required_scopes ?? []) {
      entry.scopes.add(required);
    }
    if (existing === undefined) byScope.set(scope, entry);

    if (node.capability_scope !== "" && node.capability_scope !== scope) {
      warnings.push({
        code: "capability_scope_ignored",
        node_id: node.id,
        message: `Step "${node.label}" declared credential scope "${node.capability_scope}" but ${node.capability} belongs to "${scope}". The capability decides, so "${scope}" was used.`,
      });
    }
  }

  return [...byScope.entries()]
    .sort(([a], [b]) => compareStrings(a, b))
    .map(([scope, entry]) => {
      const scopes = [...entry.scopes].sort(compareStrings);
      return {
        id: `${CREDENTIAL_PREFIX}${scope}`,
        capability_scope: scope,
        auth_type: entry.auth.type,
        label: entry.auth.label,
        ...(scopes.length === 0 ? {} : { required_scopes: scopes }),
      };
    });
}

/** The integration a node authenticates against, or `undefined` when it needs none. */
function scopeOf(planned: PlanNode, registry: Registry): string | undefined {
  const resolved = resolve(registry, planned.capability);
  if (resolved?.auth === undefined) return undefined;
  return resolved.integration.integration;
}

/** Pins the emitted versions against what this build supports. Used by a test. */
export const VERSION_PINS = {
  ffir: { writes: WRITES_FFIR_VERSION, supported: SUPPORTED_FFIR_VERSIONS },
  grammar: {
    writes: WRITES_EXPRESSION_GRAMMAR,
    supported: SUPPORTED_EXPRESSION_GRAMMARS,
  },
} as const;
