/**
 * The generation state machine.
 *
 * A sentence goes in and a validated FFIR document comes out. Every stage's
 * position is real, every failure is reported in one vocabulary, and nothing
 * here reads a clock or generates an id: both arrive as arguments, so a whole
 * document can be asserted on rather than a document with two fields excused.
 *
 * ## Why this is not in `packages/ai`
 *
 * Validation stage 5 is a compile dry-run, so something has to call both the AI
 * layer and the compiler. That something cannot be the AI layer, because the
 * moment it can import the compiler someone reaches for a platform detail from
 * inside a prompt and the claim that adding Make.com requires no AI change
 * becomes false. Naming the orchestrator is what keeps that boundary real.
 *
 * The dry-run runs from M9. `errors.ts` had already reconciled the compiler's
 * vocabulary a milestone earlier, which is why wiring the gate is a handful of
 * lines rather than a translation layer.
 *
 * ## Failures are collected within a stage and stop between them
 *
 * Validation returns every failure it finds, because the repair prompt needs
 * the complete list to fix a document in one retry rather than three. Between
 * stages the machine stops, because each stage's input is the previous stage's
 * output and there is nothing useful to say about parameters for a plan that
 * was never produced.
 */

import {
  assertSynthesizable,
  buildParametersRequest,
  callStructured,
  capabilitiesOf,
  emptyUsage,
  InlineRetriever,
  merge,
  PROMPT_VERSION,
  runPlan,
  validateAgainstRegistry,
  type CapabilityRetriever,
  type Effort,
  type ModelProvider,
  type NodeParameters,
  type ParametersRequestBuild,
  type ProviderUsage,
  type WorkflowPlan,
} from "@flowforge/ai";
import { compile, n8nTarget, type Target } from "@flowforge/compiler";
import {
  checkGraph,
  validateStructure,
  type FFIRDocument,
  type Warning,
} from "@flowforge/ffir";
import type { Registry } from "@flowforge/registry";

import { EventLog, LabelWatcher, type EventSink, type GenerationEvent } from "./events.js";
import {
  fromCompileError,
  fromThrown,
  fromValidationError,
  type GenerationFailure,
} from "./errors.js";
import type { Stage } from "./stages.js";

export interface GenerateInput {
  /** What the user typed. */
  prompt: string;
  registry: Registry;
  provider: ModelProvider;
  /** Defaults to the inline catalog, which is right below a few hundred capabilities. */
  retriever?: CapabilityRetriever;
  /**
   * What the compile dry-run compiles against. Defaults to n8n, the only target
   * that exists. Injectable because the gate's failure path is otherwise
   * unreachable from a fixture: the worked example compiles, which is the whole
   * point of it.
   */
  target?: Target;
  /** Generated by the caller, or carried through on iteration. */
  documentId: string;
  /** ISO 8601, supplied so this function has no clock. */
  generatedAt: string;
  onEvent?: EventSink;
  model?: string;
  effort?: Effort;
  maxTokens?: number;
}

export interface GenerationSuccess {
  ok: true;
  document: FFIRDocument;
  warnings: Warning[];
  events: GenerationEvent[];
  usage: ProviderUsage;
  plan: WorkflowPlan;
  parameters: NodeParameters;
}

export interface GenerationFailed {
  ok: false;
  failures: GenerationFailure[];
  events: GenerationEvent[];
  usage: ProviderUsage;
  /** The last stage that produced anything. Where the machine stopped. */
  stage: Stage;
  /** Present when the failure happened after pass A returned. */
  plan?: WorkflowPlan;
}

export type GenerationResult = GenerationSuccess | GenerationFailed;

export async function generate(input: GenerateInput): Promise<GenerationResult> {
  const log = new EventLog(input.onEvent);
  const usage = emptyUsage();
  const retriever = input.retriever ?? new InlineRetriever();
  const target = input.target ?? n8nTarget;
  const warnings: Warning[] = [];

  // --- Stage 1: plan -------------------------------------------------------
  log.enter("plan");
  const watcher = new LabelWatcher();

  let plan: WorkflowPlan;
  try {
    const result = await runPlan(
      input.provider,
      {
        prompt: input.prompt,
        registry: input.registry,
        retriever,
        ...(input.model === undefined ? {} : { model: input.model }),
        ...(input.effort === undefined ? {} : { effort: input.effort }),
        ...(input.maxTokens === undefined ? {} : { maxTokens: input.maxTokens }),
      },
      (event) => {
        if (event.type !== "text") return;
        for (const label of watcher.push(event.text)) {
          log.emit("plan", `Planning "${label}"...`, { step: watcher.count });
        }
      },
    );
    plan = result.plan;
    addUsage(usage, result.message.usage);
  } catch (thrown) {
    return failed(log, usage, "plan", [fromThrown("plan", thrown)]);
  }

  // --- Stage 2: retrieve ---------------------------------------------------
  // Local. The bundle build is where retrieval actually happens, so the event
  // is emitted around it rather than around a call that does not exist.
  log.enter("retrieve", { capabilities: capabilitiesOf(plan) });

  let parametersRequest: ParametersRequestBuild;
  try {
    parametersRequest = buildParametersRequest({
      plan,
      prompt: input.prompt,
      registry: input.registry,
      retriever,
      ...(input.model === undefined ? {} : { model: input.model }),
      ...(input.effort === undefined ? {} : { effort: input.effort }),
      ...(input.maxTokens === undefined ? {} : { maxTokens: input.maxTokens }),
    });
  } catch (thrown) {
    return failed(log, usage, "retrieve", [fromThrown("retrieve", thrown)], plan);
  }

  // An unknown capability belongs to the unknown-capability ladder, which is
  // M9. Until it exists, saying so plainly beats sending the model a bundle
  // with a silent hole in it.
  if (parametersRequest.bundle.unknown.length > 0) {
    warnings.push({
      code: "capability_unknown",
      message: `The plan named ${parametersRequest.bundle.unknown.join(", ")}, which this registry does not contain. Those steps have no schema and will need configuring by hand.`,
    });
  }

  // A schema that cannot describe a valid document is worth catching before
  // spending a call that can only fail.
  try {
    assertSynthesizable(parametersRequest.synthesis);
  } catch (thrown) {
    return failed(log, usage, "retrieve", [fromThrown("retrieve", thrown)], plan);
  }

  for (const issue of parametersRequest.synthesis.issues) {
    warnings.push({
      code: "capability_degraded",
      ...(issue.nodeId === undefined ? {} : { node_id: issue.nodeId }),
      message: issue.message,
    });
  }

  // --- Stage 3: parameters -------------------------------------------------
  log.enter("parameters", { nodes: plan.nodes.length });

  let parameters: NodeParameters;
  try {
    const result = await callStructured<NodeParameters>(
      input.provider,
      parametersRequest.request,
    );
    parameters = result.value;
    addUsage(usage, result.message.usage);
  } catch (thrown) {
    return failed(log, usage, "parameters", [fromThrown("parameters", thrown)], plan);
  }

  // --- Stage 4: merge ------------------------------------------------------
  log.enter("merge");

  let document: FFIRDocument;
  let mergeWarnings: Warning[];
  try {
    const merged = merge({
      plan,
      parameters,
      registry: input.registry,
      prompt: input.prompt,
      documentId: input.documentId,
      generatedAt: input.generatedAt,
      // The model that actually ran, taken from the request rather than from
      // the input, so a default that this package did not choose is still
      // recorded accurately on the document.
      generatedBy: parametersRequest.request.model,
      promptVersion: PROMPT_VERSION,
      warnings,
    });
    document = merged.document;
    mergeWarnings = merged.warnings;
  } catch (thrown) {
    return failed(log, usage, "merge", [fromThrown("merge", thrown)], plan);
  }

  // --- Stage 5: validate ---------------------------------------------------
  log.enter("validate");

  const failures = validateDocument(document, input.registry);
  if (failures.length > 0) {
    return failed(log, usage, "validate", failures, plan);
  }

  // --- Stage 6: compile dry-run --------------------------------------------
  // Validation stage 5 in AI_SPEC's numbering. The gate that makes "it renders
  // on the canvas" and "it will export" the same claim: without it a user can
  // iterate in chat for a minute and hit the failure at download time. The
  // compiler is a pure function with no I/O, so running it and throwing the
  // result away is cheap.
  log.enter("compile", { target: target.key });

  const compiled = compile(document, input.registry, target);
  if (!compiled.ok) {
    return failed(log, usage, "compile", compiled.errors.map(fromCompileError), plan);
  }

  // The output is deliberately discarded. Returning it would make this the
  // export path, and export happens later against a document the user may have
  // edited; a caller holding a stale artifact from generation time is a bug
  // waiting to be written. The gate answers one question: does this compile.
  log.emit("compile", "Ready", { warnings: mergeWarnings.length });

  return {
    ok: true,
    document,
    warnings: mergeWarnings,
    events: log.events,
    usage,
    plan,
    parameters,
  };
}

/**
 * Validation stages 0 through 4.
 *
 * Stage 0 short-circuits into stage 1 inside `validateStructure`, because
 * handing an unbounded document to a schema validator is the attack the limits
 * exist to prevent. Stages 2, 3, and 4 all run even when one of them fails, so
 * a document with an unknown capability and a bad expression comes back with
 * both rather than with one and then, a repair later, the other.
 *
 * Validation stage 5, the compile dry-run, is not here: it needs the compiler,
 * so it runs in `generate` itself rather than in a function `ffir` and
 * `registry` could have shared.
 */
export function validateDocument(
  document: FFIRDocument,
  registry: Registry,
): GenerationFailure[] {
  const structure = validateStructure(document);
  if (!structure.ok) {
    return structure.errors.map((error) => fromValidationError("validate", error));
  }

  return [
    ...validateAgainstRegistry(document, registry).errors,
    ...checkGraph(document).errors,
  ].map((error) => fromValidationError("validate", error));
}

function failed(
  log: EventLog,
  usage: ProviderUsage,
  stage: Stage,
  failures: GenerationFailure[],
  plan?: WorkflowPlan,
): GenerationFailed {
  return {
    ok: false,
    failures,
    events: log.events,
    usage,
    stage,
    ...(plan === undefined ? {} : { plan }),
  };
}

/** Totals across every call in one generation. Mutated in place; never read mid-stage. */
function addUsage(total: ProviderUsage, add: ProviderUsage): void {
  total.inputTokens += add.inputTokens;
  total.outputTokens += add.outputTokens;
  total.cacheReadInputTokens += add.cacheReadInputTokens;
  total.cacheCreationInputTokens += add.cacheCreationInputTokens;
}
